### ISSUE TITLE
I have no idea how to fix the Markbot issues.

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/fastness-fixer#1]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/55094325/97022238-debd8b00-1521-11eb-8c05-0af7204a0f5a.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/55094325/97022503-31974280-1522-11eb-8bd8-7bd03e701f3f.png">

@hellachella
@jessjodoin

**Comment by JessJodoin** [comment]
That image should be renamed snail.jpg

**Comment by Samirahajiragab** [comment]
Thanks that was easy to fix 😊
 have a great reading week!😊😊😊
